window.MUMBLE_POSTS = [
  {
    id: 1,
    platform: "instagram",
    carousel: 1,
    slide: 1,
    filename: "IG_01_Speak_It_Types_Where_You_Work.png",
    stage: "awareness",
    kicker: "VOICE-FIRST WRITING",
    headline: "Speak. It types where you work.",
    body: "Press Ctrl+Win, speak, press again. Clean text lands at your cursor.",
    cta: "Meet Mumble",
    visual: "wave",
    accent: "gold",
    caption: "Your voice can be the first draft. Press Ctrl+Win, speak, press again—and Mumble pastes clean text at your cursor. #Mumble #VoiceToText #Windows",
    alt: "Mumble's gold waveform and floating Island flowing into a blinking text cursor on a black background."
  },
  {
    id: 2,
    platform: "instagram",
    carousel: 1,
    slide: 2,
    filename: "IG_02_Voice_To_Text_Follows_Your_Cursor.png",
    stage: "awareness",
    kicker: "WORK WHERE YOU WORK",
    headline: "Voice-to-text that follows your cursor.",
    body: "Dictate where you already write—email, chat, documents, or code.",
    cta: "Keep your workflow. Add voice.",
    visual: "apps",
    accent: "gold",
    caption: "Mumble is a layer over the tools you already use. Dictate into email, chat, documents, or code without moving your work somewhere else. #Productivity #Dictation",
    alt: "A gold Mumble Island connected to four generic email, chat, document, and code windows."
  },
  {
    id: 3,
    platform: "instagram",
    carousel: 1,
    slide: 3,
    filename: "IG_03_One_Shortcut_One_Thought.png",
    stage: "awareness",
    kicker: "THE EVERYDAY LOOP",
    headline: "One shortcut. One thought. Done.",
    body: "Ctrl+Win starts and stops everyday dictation.",
    cta: "Try the shortcut",
    visual: "hotkey",
    accent: "gold",
    caption: "Press Ctrl+Win. Speak naturally. Press it again. That is Mumble's everyday dictation loop. Save the shortcut for later. #WindowsTips #VoiceTyping",
    alt: "An oversized Ctrl plus Win keycap above a gold waveform and a pasted-text confirmation."
  },
  {
    id: 4,
    platform: "instagram",
    carousel: 1,
    slide: 4,
    filename: "IG_04_Private_Starts_With_Local.png",
    stage: "awareness",
    kicker: "LOCAL BY DEFAULT",
    headline: "Private starts with local.",
    body: "Local transcription is the default. Audio is processed on your PC unless you explicitly choose Cloud transcription.",
    cta: "Keep control",
    visual: "privacy",
    accent: "green",
    caption: "Mumble starts with Local transcription. Your audio is processed on your PC unless you explicitly switch to Cloud transcription. Privacy begins with a clear default. #Privacy #LocalFirst",
    alt: "A gold waveform entering a computer chip protected by a green lock, with Local marked as the default."
  },
  {
    id: 5,
    platform: "instagram",
    carousel: 1,
    slide: 5,
    filename: "IG_05_Core_Dictation_Even_Offline.png",
    stage: "conversion",
    kicker: "OFFLINE CORE",
    headline: "Core dictation, even offline.",
    body: "With Local transcription selected and Pro Mode off, Mumble's core dictation workflow can stay offline.",
    cta: "Use Local mode",
    visual: "offline",
    accent: "green",
    caption: "Choose Local transcription and turn Pro Mode off when you want Mumble's core dictation workflow to stay offline. Clear controls, no vague promises. #OfflineTools #LocalAI",
    alt: "A Local mode switch, disconnected network icon, gold waveform, and text cursor showing an offline dictation path."
  },
  {
    id: 6,
    platform: "instagram",
    carousel: 1,
    slide: 6,
    filename: "IG_06_AI_Gets_Text_Not_Audio.png",
    stage: "conversion",
    kicker: "OPTIONAL AI POLISH",
    headline: "AI polish gets the text—not the audio.",
    body: "When cloud Pro Mode is enabled, Mumble sends transcript text to your chosen provider. Audio stays out of that polish step.",
    cta: "Choose how Mumble polishes",
    visual: "textpath",
    accent: "teal",
    qualifier: "Requires a configured AI provider; provider charges may apply.",
    caption: "Cloud Pro Mode sends transcript text—not audio—to the AI provider you choose. Mumble keeps transcription and AI polish as separate, understandable steps. #PrivacyByDesign #AIWriting",
    alt: "A waveform remains behind a lock while only a text document travels to a provider-neutral AI chip."
  },
  {
    id: 7,
    platform: "instagram",
    carousel: 2,
    slide: 1,
    filename: "IG_07_Meet_The_Deck.png",
    stage: "consideration",
    kicker: "ONE PINNED WORKSPACE",
    headline: "Meet the Deck.",
    body: "Search transcripts, clipboard history, saved prompts, and favourites in one pinned workspace.",
    cta: "Everything, one shortcut away",
    visual: "deck",
    accent: "teal",
    caption: "The Deck brings transcripts, clipboard history, saved prompts, and favourites into one searchable workspace. Open it with Ctrl+Alt+D. #ProductivityTools #Mumble",
    alt: "A black-and-gold Mumble Deck with search, transcript, clipboard, prompt, and favourite sections."
  },
  {
    id: 8,
    platform: "instagram",
    carousel: 2,
    slide: 2,
    filename: "IG_08_Your_Clipboard_Has_A_Memory.png",
    stage: "consideration",
    kicker: "SEARCHABLE CLIPBOARD HISTORY",
    headline: "Your clipboard has a memory.",
    body: "Mumble can retain copied text and images in searchable clipboard history.",
    cta: "Find what you copied",
    visual: "clipboard",
    accent: "teal",
    caption: "Copied text and images do not have to disappear into clipboard limbo. Mumble can retain them in searchable clipboard history inside the Deck. #ClipboardManager #WindowsApps",
    alt: "Stacked clipboard cards containing text and abstract image thumbnails inside Mumble's Deck."
  },
  {
    id: 9,
    platform: "instagram",
    carousel: 2,
    slide: 3,
    filename: "IG_09_25_Ways_To_Work_With_Text.png",
    stage: "consideration",
    kicker: "20 BUILT-IN + 5 CUSTOM",
    headline: "25 ways to work with text.",
    body: "Summarise, Focus, Reply, Action items and more—plus five custom preset slots.",
    cta: "Pick a preset. Press Go.",
    visual: "presets",
    accent: "purple",
    qualifier: "AI transformations require a configured provider or compatible local model; provider charges may apply.",
    caption: "Mumble includes 20 built-in presets—from Summarise and Focus to Reply and Action items—plus five custom slots for your own workflows. #WritingTools #AIPrompts",
    alt: "A five-by-five grid of glass preset chips, including Summarise, Focus, Reply, Action items, and Custom."
  },
  {
    id: 10,
    platform: "instagram",
    carousel: 2,
    slide: 4,
    filename: "IG_10_Highlight_Capture_Transform.png",
    stage: "consideration",
    kicker: "REUSE EXISTING TEXT",
    headline: "Highlight it. Capture it. Transform it.",
    body: "Pull selected text from another app into the Deck, then run a preset or action.",
    cta: "Open the Deck",
    visual: "capture",
    accent: "teal",
    qualifier: "AI transformations require a configured provider or compatible local model; provider charges may apply.",
    caption: "Highlight text in another app, capture it into the Deck, then run the preset or action you need. Existing text becomes useful input. #Workflow #TextTools",
    alt: "Highlighted text moving through a Capture button into a Mumble preset and polished result."
  },
  {
    id: 11,
    platform: "instagram",
    carousel: 2,
    slide: 5,
    filename: "IG_11_Rough_Idea_To_Structured_Prompt.png",
    stage: "consideration",
    kicker: "PROMPT MODE",
    headline: "Rough idea → structured prompt.",
    body: "Turn on Prompt from the Island, dictate the idea, and Mumble shapes it into a structured AI prompt.",
    cta: "Say it before you overthink it",
    visual: "prompt",
    accent: "purple",
    qualifier: "Prompt shaping requires a configured provider or compatible local model; provider charges may apply.",
    caption: "Turn on Prompt from the Island, dictate the rough idea, and Mumble shapes it into a structured AI prompt with a clearer role, task, and constraints. #PromptEngineering #Mumble",
    alt: "A purple Prompt chip beside a rough dictated idea and structured role, task, and constraints fields."
  },
  {
    id: 12,
    platform: "instagram",
    carousel: 2,
    slide: 6,
    filename: "IG_12_A_Meeting_Is_More_Than_Audio.png",
    stage: "awareness",
    kicker: "MEETING MODE",
    headline: "A meeting is more than audio.",
    body: "Record up to four hours from your selected microphone—or import an audio file—then transcribe, replay, and review speaker-labelled segments.",
    cta: "Open Meetings",
    visual: "meetingflow",
    accent: "gold",
    caption: "Record room audio from the selected microphone or import an audio file, then transcribe, replay, and review speaker-labelled segments in Mumble. #MeetingNotes #Transcription",
    alt: "A meeting flow showing selected-microphone recording or audio import, transcript segments with speaker labels, replay, and processing icons."
  },
  {
    id: 13,
    platform: "instagram",
    carousel: 3,
    slide: 1,
    filename: "IG_13_From_Meeting_To_Next_Steps.png",
    stage: "consideration",
    kicker: "STRUCTURED MEETING OUTPUT",
    headline: "From meeting to next steps.",
    body: "With an AI provider configured, summarise and extract action items, key decisions, and open questions.",
    cta: "Leave with the work clear",
    visual: "extract",
    accent: "coral",
    qualifier: "Requires a configured AI provider; provider charges may apply.",
    caption: "With an AI provider configured, Mumble can turn a meeting transcript into a summary, action items, key decisions, and open questions. #MeetingProductivity #ActionItems",
    alt: "A speaker-labelled meeting transcript feeding summary, action items, key decisions, and open questions cards."
  },
  {
    id: 14,
    platform: "instagram",
    carousel: 3,
    slide: 2,
    filename: "IG_14_Read_11_File_Formats_Aloud.png",
    stage: "awareness",
    kicker: "MUMBLE READER",
    headline: "Read 11 file formats aloud.",
    body: "PDF, DOCX, EPUB, HTML, RTF, Markdown, TXT, CSV, ODT, PPTX, and XLSX.",
    cta: "Open it in Reader",
    visual: "formats",
    accent: "blue",
    qualifier: "Voice playback requires a configured TTS provider; provider charges may apply.",
    caption: "Open PDF, DOCX, EPUB, HTML, RTF, Markdown, TXT, CSV, ODT, PPTX, or XLSX in Mumble Reader and follow the live word highlight. #TextToSpeech #Reader",
    alt: "Eleven file-format badges surrounding a document with one word highlighted in gold."
  },
  {
    id: 15,
    platform: "instagram",
    carousel: 3,
    slide: 3,
    filename: "IG_15_Search_What_You_See_Or_Say.png",
    stage: "awareness",
    kicker: "VOICE + SELECTION SEARCH",
    headline: "Search what you see—or say.",
    body: "Highlight text and press Ctrl+Alt+S, or speak a query. Choose Perplexity, Google, or Brave.",
    cta: "Search without retyping",
    visual: "search",
    accent: "rose",
    caption: "Highlight text and press Ctrl+Alt+S—or speak a query when nothing is selected. Mumble can search with Perplexity, Google, or Brave. #SearchTips #VoiceSearch",
    alt: "Highlighted text and a gold waveform converging into a search bar with Perplexity, Google, and Brave labels."
  },
  {
    id: 16,
    platform: "instagram",
    carousel: 3,
    slide: 4,
    filename: "IG_16_Your_Voice_Workflow_In_Numbers.png",
    stage: "consideration",
    kicker: "LOCAL USAGE INSIGHTS",
    headline: "Your voice workflow, in numbers.",
    body: "Track words, pace, streaks, activity, and mode mix. Time saved stays clearly labelled as an estimate.",
    cta: "See your Stats",
    visual: "stats",
    accent: "green",
    caption: "Mumble Stats tracks words, pace, streaks, activity, and mode mix from your usage. Time saved remains clearly labelled as an estimate—because trust beats hype. #PersonalAnalytics",
    alt: "A black-and-gold Stats dashboard with words, pace, streak, activity, mode mix, and an Estimated badge."
  },
  {
    id: 17,
    platform: "instagram",
    carousel: 3,
    slide: 5,
    filename: "IG_17_Free_Windows_No_Account.png",
    stage: "conversion",
    kicker: "FREE + MIT LICENSED",
    headline: "Free Windows download. No account to start.",
    body: "Mumble is free to download for Windows. Its code is MIT-licensed, and Local mode needs no account or API key.",
    cta: "Download Mumble",
    visual: "license",
    accent: "gold",
    caption: "Mumble is free to download for Windows. Its code is MIT-licensed, and Local mode needs no account or API key to start. #Windows #VoiceToText",
    alt: "The Mumble icon beside Free Windows download, MIT-licensed code, and No account for Local mode badges."
  },
  {
    id: 18,
    platform: "instagram",
    carousel: 3,
    slide: 6,
    filename: "IG_18_Ready_When_Your_Cursor_Is.png",
    stage: "conversion",
    kicker: "START WITH CTRL+WIN",
    headline: "Ready when your cursor is.",
    body: "Install Mumble, press Ctrl+Win, and start dictating into the app already in front of you.",
    cta: "Download for Windows — Free",
    visual: "download",
    accent: "gold",
    caption: "Install Mumble, place your cursor where you want the words, and press Ctrl+Win. Voice-to-text starts where your work already is. Download for Windows—free. #Mumble",
    alt: "A Mumble download card with a Ctrl plus Win keycap, floating Island, and blinking cursor."
  },
  {
    id: 19,
    platform: "x",
    carousel: 4,
    slide: 1,
    filename: "X_19_The_Mumble_Data_Path.png",
    stage: "consideration",
    kicker: "THE DATA PATH",
    headline: "The Mumble data path, in one diagram.",
    body: "Voice → Local transcription by default → optional text polish → cursor. Cloud transcription is a separate opt-in.",
    cta: "See exactly what moves",
    visual: "datapath",
    accent: "teal",
    qualifier: "Optional AI shaping requires a configured provider or compatible local model; provider charges may apply.",
    caption: "Voice → Local transcription by default → optional text polish → cursor. Cloud transcription is a separate opt-in.",
    alt: "A technical pipeline showing voice, default local transcription, optional text polish, and text pasted at the cursor."
  },
  {
    id: 20,
    platform: "x",
    carousel: 4,
    slide: 2,
    filename: "X_20_Local_By_Default_Cloud_By_Choice.png",
    stage: "conversion",
    kicker: "CHOOSE YOUR STT LANE",
    headline: "Local by default. Cloud by choice.",
    body: "Use on-device faster-whisper, or explicitly select Cloud transcription with a supported provider.",
    cta: "Set your transcription lane",
    visual: "lanes",
    accent: "green",
    qualifier: "Cloud transcription requires a configured provider; provider charges may apply.",
    caption: "Use on-device faster-whisper by default, or explicitly select Cloud transcription with a supported provider. Mumble makes the choice visible instead of burying it.",
    alt: "Parallel Local and Cloud transcription lanes with Local visibly selected as the default."
  },
  {
    id: 21,
    platform: "x",
    carousel: 4,
    slide: 3,
    filename: "X_21_Your_AI_Key_Your_Provider.png",
    stage: "conversion",
    kicker: "OPTIONAL PROVIDER CONTROL",
    headline: "Your AI key. Your provider.",
    body: "AI shaping is optional. In cloud Pro Mode, Mumble sends transcript text—not audio—to the supported provider you select.",
    cta: "Bring your own AI",
    visual: "providers",
    accent: "purple",
    qualifier: "Requires a configured AI provider; provider charges may apply.",
    caption: "AI shaping is optional. In cloud Pro Mode, Mumble sends transcript text—not audio—to the supported provider you choose, using your own key.",
    alt: "A transcript text card branching to several provider-neutral AI chips while the audio waveform remains local."
  },
  {
    id: 22,
    platform: "x",
    carousel: 4,
    slide: 4,
    filename: "X_22_MIT_Licensed_Free_To_Start.png",
    stage: "conversion",
    kicker: "MIT-LICENSED SOFTWARE",
    headline: "MIT-licensed. Free to start.",
    body: "Mumble's code carries the MIT Licence. The Windows download is free, and Local mode needs no account or API key.",
    cta: "Download for Windows",
    visual: "license",
    accent: "gold",
    caption: "Mumble's code carries the MIT Licence. The Windows download is free, and Local mode needs no account or API key.",
    alt: "The Mumble icon over a black-and-gold card labelled MIT-licensed, Free Windows download, and No account for Local mode."
  },
  {
    id: 23,
    platform: "x",
    carousel: 4,
    slide: 5,
    filename: "X_23_Four_Defaults_Worth_Remembering.png",
    stage: "awareness",
    kicker: "DEFAULT SHORTCUTS",
    headline: "Four defaults worth remembering.",
    body: "Ctrl+Win record · Ctrl+Alt+V paste latest · Ctrl+Alt+D Deck · Ctrl+Alt+S search.",
    cta: "Save this shortcut card",
    visual: "hotkey",
    accent: "gold",
    caption: "Mumble defaults: Ctrl+Win record · Ctrl+Alt+V paste latest · Ctrl+Alt+D open Deck · Ctrl+Alt+S search. Save the card; customise them in Settings.",
    alt: "Four glass keycap tiles labelled Record, Paste latest, Deck, and Search with their default shortcuts."
  },
  {
    id: 24,
    platform: "x",
    carousel: 4,
    slide: 6,
    filename: "X_24_A_Layer_Not_A_Destination.png",
    stage: "awareness",
    kicker: "KEEP YOUR TOOLS",
    headline: "Mumble is a layer, not a destination.",
    body: "Dictate into email, chat, documents, code editors, or another focused text field.",
    cta: "Keep your workflow. Add voice.",
    visual: "apps",
    accent: "gold",
    caption: "Mumble does not ask you to write inside a new editor. It sits over the workflow you already have and pastes at the focused cursor.",
    alt: "The Mumble Island floating above generic email, chat, document, and code-editor windows."
  },
  {
    id: 25,
    platform: "x",
    carousel: 5,
    slide: 1,
    filename: "X_25_Say_It_Then_Clean_It.png",
    stage: "consideration",
    kicker: "FROM SPEECH TO CLEAN TEXT",
    headline: "What you say isn't what you have to paste.",
    body: "Local cleanup fixes punctuation and capitalisation; optional AI can reshape the text further.",
    cta: "Speak naturally",
    visual: "cleanup",
    accent: "teal",
    qualifier: "Optional AI shaping requires a configured provider or compatible local model; provider charges may apply.",
    caption: "Speak naturally. Mumble's local cleanup handles punctuation and capitalisation; optional AI can reshape the transcript further when you choose it.",
    alt: "An example raw dictation beside a clean, punctuated paragraph labelled Local cleanup and Optional AI."
  },
  {
    id: 26,
    platform: "x",
    carousel: 5,
    slide: 2,
    filename: "X_26_20_Built_In_5_Custom.png",
    stage: "consideration",
    kicker: "25 PRESET SLOTS",
    headline: "20 built-ins. 5 of your own.",
    body: "Summarise, Focus, Deep Thinking, Reply, Improve, Action items, Humanise, Merge, and more.",
    cta: "Build your preset row",
    visual: "presets",
    accent: "purple",
    qualifier: "AI transformations require a configured provider or compatible local model; provider charges may apply.",
    caption: "Mumble ships with 20 built-in text presets and five custom slots. Summarise, Focus, Reply, Improve, Action items, Humanise, Merge—and more.",
    alt: "A grid of twenty labelled Mumble preset chips followed by five outlined custom preset slots."
  },
  {
    id: 27,
    platform: "x",
    carousel: 5,
    slide: 3,
    filename: "X_27_Select_Several_Press_Go.png",
    stage: "consideration",
    kicker: "MULTI-ITEM WORKFLOWS",
    headline: "Select several items. Press Go.",
    body: "Combine transcript, clipboard, and prompt items; choose a preset or action; return the result to your cursor.",
    cta: "Turn fragments into output",
    visual: "combine",
    accent: "rose",
    qualifier: "AI transformations require a configured provider or compatible local model; provider charges may apply.",
    caption: "Tick transcripts, clipboard items, or saved prompts in the Deck. Choose a preset or action, press Go, and return one result to your cursor.",
    alt: "Checked transcript, clipboard, and prompt rows converging into one polished output card."
  },
  {
    id: 28,
    platform: "x",
    carousel: 5,
    slide: 4,
    filename: "X_28_Keep_Both_Versions.png",
    stage: "consideration",
    kicker: "PRE-AI ⇄ POST-AI",
    headline: "Keep both versions.",
    body: "History can show Pre-AI and Post-AI text, keeping the raw transcript visible beside the polished output.",
    cta: "Compare before you reuse",
    visual: "compare",
    accent: "purple",
    qualifier: "AI-polished output requires a configured provider or compatible local model; provider charges may apply.",
    caption: "Mumble History can show Pre-AI and Post-AI text. Compare the raw transcript with the polished output before you reuse it.",
    alt: "A Pre-AI to Post-AI toggle above raw transcript and polished-output panels."
  },
  {
    id: 29,
    platform: "x",
    carousel: 5,
    slide: 5,
    filename: "X_29_One_Meeting_Five_Exports.png",
    stage: "consideration",
    kicker: "FIVE EXPORT ROUTES",
    headline: "One meeting. Five export routes.",
    body: "Export to TXT, Markdown, JSON, HTML, or the clipboard.",
    cta: "Send it to the next tool",
    visual: "export",
    accent: "blue",
    caption: "A Mumble meeting can leave as TXT, Markdown, JSON, HTML, or clipboard text. Pick the format the next tool needs.",
    alt: "A meeting transcript branching into TXT, Markdown, JSON, HTML, and clipboard export tiles."
  },
  {
    id: 30,
    platform: "x",
    carousel: 5,
    slide: 6,
    filename: "X_30_Reader_Remembers_The_Page.png",
    stage: "consideration",
    kicker: "RESUMABLE READING",
    headline: "Your Reader remembers the page.",
    body: "The document library tracks progress and resumes where you left off.",
    cta: "Close it. Come back later.",
    visual: "reader",
    accent: "blue",
    qualifier: "Voice playback requires a configured TTS provider; provider charges may apply.",
    caption: "Mumble Reader keeps a document library, tracks progress, and resumes where you left off. Close the document; come back when you are ready.",
    alt: "A Mumble Reader library card with a bookmark and gold reading-progress track."
  },
  {
    id: 31,
    platform: "x",
    carousel: 6,
    slide: 1,
    filename: "X_31_History_That_Stays_Useful.png",
    stage: "consideration",
    kicker: "SEARCHABLE HISTORY",
    headline: "History that stays useful.",
    body: "Search, filter, sort, favourite, and review transcript details including words, duration, and WPM.",
    cta: "Find the line again",
    visual: "history",
    accent: "teal",
    caption: "Search, filter, sort, and favourite Mumble history. Review transcript details such as words, duration, and WPM when you need the line again.",
    alt: "Mumble History with a search field, filter chips, favourite star, and transcript metadata."
  },
  {
    id: 32,
    platform: "x",
    carousel: 6,
    slide: 2,
    filename: "X_32_Local_Transcription_Sized_To_The_Machine.png",
    stage: "awareness",
    kicker: "HARDWARE-AWARE MODELS",
    headline: "Local transcription sized to the machine.",
    body: "Mumble supports hardware-aware local model tiers, from lighter models to higher-accuracy options.",
    cta: "Choose the fit in Settings",
    visual: "hardware",
    accent: "sand",
    caption: "Mumble supports hardware-aware local transcription tiers, from lighter models to higher-accuracy options. Choose the fit in Settings—without invented speed claims.",
    alt: "Weak, Mid, and Powerful hardware tier cards connected to progressively larger local transcription model blocks."
  },
  {
    id: 33,
    platform: "x",
    carousel: 6,
    slide: 3,
    filename: "X_33_No_Account_No_Telemetry.png",
    stage: "conversion",
    kicker: "LOCAL CORE DATA",
    headline: "No account required. No telemetry.",
    body: "Core settings, history, and statistics are stored on your device.",
    cta: "Use it without signing in",
    visual: "localvault",
    accent: "green",
    caption: "No account is required to start Mumble, and the app has no telemetry. Core settings, history, and statistics are stored on your device.",
    alt: "A device-shaped vault containing Settings, History, and Stats file cards with a No telemetry badge."
  },
  {
    id: 34,
    platform: "x",
    carousel: 6,
    slide: 4,
    filename: "X_34_Stats_That_Label_Estimates.png",
    stage: "consideration",
    kicker: "PROOF OVER HYPE",
    headline: "A stats page that labels estimates.",
    body: "Words and usage come from local activity; time saved is explicitly presented as estimated.",
    cta: "Proof over hype",
    visual: "stats",
    accent: "green",
    caption: "Mumble's words and usage stats come from local activity. Time saved is explicitly labelled as estimated—because a useful number should also be an honest one.",
    alt: "A Stats dashboard with local-activity tiles and a clearly visible Estimated label on time saved."
  },
  {
    id: 35,
    platform: "x",
    carousel: 6,
    slide: 5,
    filename: "X_35_Windows_Dictation_Free.png",
    stage: "conversion",
    kicker: "DOWNLOAD FOR WINDOWS",
    headline: "Windows dictation. Free to download.",
    body: "MIT-licensed Windows dictation, free to download, with no account or API key required for Local mode.",
    cta: "Download Mumble — Free",
    visual: "download",
    accent: "gold",
    caption: "Mumble is MIT-licensed Windows voice-to-text, free to download, with no account or API key required for Local mode. Place the cursor and press Ctrl+Win.",
    alt: "A wide Mumble download hero with the app icon, floating Island, Windows badge, and gold download button."
  },
  {
    id: 36,
    platform: "tiktok",
    carousel: 7,
    slide: 1,
    filename: "TT_36_Thoughts_Should_Not_Wait.png",
    stage: "awareness",
    kicker: "VOICE-FIRST DRAFTING",
    headline: "Your thought shouldn't wait for a blank page.",
    body: "Press Ctrl+Win. Speak it. Let clean text land at the cursor.",
    cta: "Try the voice-first workflow",
    visual: "wave",
    accent: "gold",
    caption: "Blank page? Press Ctrl+Win, speak the thought, and let Mumble place clean text at the cursor. #VoiceToText #Windows #Productivity",
    alt: "A tall blank document crossed by a gold waveform that resolves into clean text at a cursor."
  },
  {
    id: 37,
    platform: "tiktok",
    carousel: 7,
    slide: 2,
    filename: "TT_37_Press_Speak_Press_Again.png",
    stage: "awareness",
    kicker: "THE MUMBLE LOOP",
    headline: "Press. Speak. Press again.",
    body: "That is Mumble's everyday dictation loop.",
    cta: "Save this shortcut",
    visual: "hotkey",
    accent: "gold",
    caption: "Ctrl+Win → speak → Ctrl+Win again. That is the everyday Mumble loop. Save this for your next Windows setup. #WindowsTips #Dictation",
    alt: "Three vertical panels showing a Ctrl plus Win keycap, a listening waveform, and a pasted confirmation."
  },
  {
    id: 38,
    platform: "tiktok",
    carousel: 7,
    slide: 3,
    filename: "TT_38_One_Voice_Four_Workspaces.png",
    stage: "awareness",
    kicker: "DICTATE WHERE YOU WORK",
    headline: "One voice. Four workspaces.",
    body: "Email · chat · document · code editor. Mumble types into the focused field.",
    cta: "Keep the apps you already use",
    visual: "apps",
    accent: "gold",
    caption: "Email, chat, document, code editor—Mumble types into the focused field instead of moving your work into another app. #Workflow #VoiceTyping",
    alt: "A vertical cascade of generic email, chat, document, and code windows under the Mumble Island."
  },
  {
    id: 39,
    platform: "tiktok",
    carousel: 7,
    slide: 4,
    filename: "TT_39_Messy_Thought_Clean_Paragraph.png",
    stage: "awareness",
    kicker: "SPEAK NATURALLY",
    headline: "Messy thought in. Clean paragraph out.",
    body: "Speak naturally; Mumble handles the first cleanup pass.",
    cta: "Stop editing the first draft in your head",
    visual: "cleanup",
    accent: "teal",
    qualifier: "Optional AI shaping requires a configured provider or compatible local model; provider charges may apply.",
    caption: "Say the rough version first. Mumble handles the initial punctuation and capitalisation cleanup, with optional AI shaping when you choose it. #WritingTips",
    alt: "A rough dictated phrase transforming into a clean, punctuated paragraph labelled Example."
  },
  {
    id: 40,
    platform: "tiktok",
    carousel: 7,
    slide: 5,
    filename: "TT_40_What_Leaves_Your_PC.png",
    stage: "awareness",
    kicker: "CLEAR PRIVACY LANES",
    headline: "What actually leaves your PC?",
    body: "Local STT: audio stays. Cloud STT: audio is sent only when selected. Cloud Pro Mode: transcript text goes to your chosen AI.",
    cta: "Privacy should be understandable",
    visual: "lanes",
    accent: "green",
    qualifier: "Cloud transcription and cloud AI require configured providers; provider charges may apply.",
    caption: "Local STT keeps audio on-device. Cloud STT sends audio only when selected. Cloud Pro Mode sends transcript text to your chosen AI. Clear lanes matter. #Privacy",
    alt: "Three labelled data lanes for Local transcription, optional Cloud transcription, and optional cloud AI polish."
  },
  {
    id: 41,
    platform: "tiktok",
    carousel: 8,
    slide: 1,
    filename: "TT_41_Deck_Is_Your_Working_Memory.png",
    stage: "awareness",
    kicker: "CTRL+ALT+D",
    headline: "The Deck is your working memory.",
    body: "Transcripts, clipboard items, prompts, and favourites—searchable in one panel.",
    cta: "Open with Ctrl+Alt+D",
    visual: "deck",
    accent: "teal",
    caption: "Transcripts, clipboard items, saved prompts, and favourites—all searchable in the Deck. Open it with Ctrl+Alt+D. #ProductivityApp #Mumble",
    alt: "A tall Mumble Deck showing searchable transcript, clipboard, prompt, and favourite cards."
  },
  {
    id: 42,
    platform: "tiktok",
    carousel: 8,
    slide: 2,
    filename: "TT_42_Copied_Yesterday_Find_Today.png",
    stage: "awareness",
    kicker: "CLIPBOARD HISTORY",
    headline: "Copied it yesterday? Find it today.",
    body: "Mumble's clipboard history can retain copied text and images.",
    cta: "Search the Deck",
    visual: "clipboard",
    accent: "teal",
    caption: "Copied text and images can stay searchable inside Mumble's clipboard history. Open the Deck instead of copying everything twice. #Clipboard #WindowsApps",
    alt: "A dated vertical timeline of copied text cards and abstract image thumbnails in the Deck."
  },
  {
    id: 43,
    platform: "tiktok",
    carousel: 8,
    slide: 3,
    filename: "TT_43_The_Four_Step_Reuse_Loop.png",
    stage: "consideration",
    kicker: "TURN INPUT INTO OUTPUT",
    headline: "The four-step reuse loop.",
    body: "Highlight → Capture → choose a preset → paste the result.",
    cta: "Make existing text useful again",
    visual: "capture",
    accent: "rose",
    qualifier: "AI transformations require a configured provider or compatible local model; provider charges may apply.",
    caption: "Highlight → Capture → choose a preset → paste the result. Mumble turns existing text into usable input for the next task. #WorkflowHack #TextTools",
    alt: "Four numbered vertical stages showing Highlight, Capture, Preset, and Paste."
  },
  {
    id: 44,
    platform: "tiktok",
    carousel: 8,
    slide: 4,
    filename: "TT_44_Do_Not_Stop_At_The_Transcript.png",
    stage: "awareness",
    kicker: "MEETING INTELLIGENCE",
    headline: "Don't stop at the transcript.",
    body: "Record microphone audio or import a recording. Mumble can apply speaker labels; with AI configured, summarise and extract actions, decisions, and questions.",
    cta: "Turn the meeting into next steps",
    visual: "extract",
    accent: "coral",
    qualifier: "Meeting analysis requires a configured AI provider; provider charges may apply.",
    caption: "Record from the selected microphone or import audio. Mumble can apply speaker labels; with AI configured, it can summarise and extract actions, decisions, and open questions. #MeetingNotes #ActionItems",
    alt: "Speaker-labelled transcript cards feeding action item, decision, summary, and open-question cards."
  },
  {
    id: 45,
    platform: "tiktok",
    carousel: 8,
    slide: 5,
    filename: "TT_45_PDF_Today_PPTX_Tomorrow.png",
    stage: "awareness",
    kicker: "11 READER FORMATS",
    headline: "PDF today. PPTX tomorrow.",
    body: "Reader supports 11 formats and highlights each word during playback.",
    cta: "Build a reading library",
    visual: "formats",
    accent: "blue",
    qualifier: "Voice playback requires a configured TTS provider; provider charges may apply.",
    caption: "PDF, DOCX, EPUB, HTML, RTF, Markdown, TXT, CSV, ODT, PPTX, XLSX—Mumble Reader supports all 11 with live word highlighting. #Reader #TextToSpeech",
    alt: "A vertical stream of eleven file-format badges entering a document with a gold-highlighted word."
  },
  {
    id: 46,
    platform: "tiktok",
    carousel: 9,
    slide: 1,
    filename: "TT_46_Search_Without_Retyping.png",
    stage: "awareness",
    kicker: "CTRL+ALT+S",
    headline: "Search without retyping the query.",
    body: "Highlight text or speak it; send the search to Perplexity, Google, or Brave.",
    cta: "Press Ctrl+Alt+S",
    visual: "search",
    accent: "rose",
    caption: "Highlight a query or speak it, then send the search to Perplexity, Google, or Brave with Ctrl+Alt+S. #VoiceSearch #WindowsTips",
    alt: "Highlighted text and a voice waveform entering a vertical search card with three engine labels."
  },
  {
    id: 47,
    platform: "tiktok",
    carousel: 9,
    slide: 2,
    filename: "TT_47_There_Is_A_Preset_For_That.png",
    stage: "consideration",
    kicker: "20 BUILT-IN + 5 CUSTOM",
    headline: "There is probably a preset for that.",
    body: "Summarise · Focus · Reply · Improve · Humanise · Merge · Action items—and more.",
    cta: "Pick one. Press Go.",
    visual: "presets",
    accent: "purple",
    qualifier: "AI transformations require a configured provider or compatible local model; provider charges may apply.",
    caption: "Summarise, Focus, Reply, Improve, Humanise, Merge, Action items—and more. Mumble has 20 built-ins plus five custom slots. #WritingTools",
    alt: "A tall scrolling wall of Mumble preset chips with five custom slots at the bottom."
  },
  {
    id: 48,
    platform: "tiktok",
    carousel: 9,
    slide: 3,
    filename: "TT_48_Three_Reasons_To_Try_Mumble.png",
    stage: "conversion",
    kicker: "WHY TRY MUMBLE",
    headline: "Three reasons to try Mumble now.",
    body: "Free Windows download · MIT-licensed code · no account or API key required for Local mode.",
    cta: "Download Mumble",
    visual: "checklist",
    accent: "gold",
    caption: "Free Windows download. MIT-licensed code. No account or API key required for Local mode. Three clear reasons to try Mumble. #FreeSoftware #Windows",
    alt: "Three numbered proof cards labelled Free Windows download, MIT-licensed code, and No account or API key for Local mode."
  },
  {
    id: 49,
    platform: "tiktok",
    carousel: 9,
    slide: 4,
    filename: "TT_49_Before_You_Install_The_Facts.png",
    stage: "conversion",
    kicker: "THE FACTS FIRST",
    headline: "Before you install, here are the facts.",
    body: "Windows now · free download · MIT-licensed code · no account or API key for Local mode. Cloud transcription and AI polish are optional.",
    cta: "Choose the setup that fits",
    visual: "checklist",
    accent: "green",
    qualifier: "Cloud transcription and cloud AI require configured providers; provider charges may apply.",
    caption: "Windows now. Free download. MIT-licensed code. No account or API key for Local mode. Cloud transcription and AI polish are optional. #TechTok #Privacy",
    alt: "A checklist for Windows availability, free download, MIT-licensed code, no account for Local mode, and optional cloud features."
  },
  {
    id: 50,
    platform: "tiktok",
    carousel: 9,
    slide: 5,
    filename: "TT_50_Install_Hotkey_Voice_Text.png",
    stage: "conversion",
    kicker: "START DICTATING",
    headline: "Install → hotkey → voice → text.",
    body: "Mumble for Windows uses Ctrl+Win to turn speech into text in the focused text field.",
    cta: "Download Mumble — Free",
    visual: "download",
    accent: "gold",
    caption: "Install Mumble for Windows, place the cursor, press Ctrl+Win, and speak. Download Mumble—free. #Mumble #VoiceToText #Windows",
    alt: "A vertical Mumble end card with the app icon, Ctrl plus Win keycap, gold waveform, text cursor, and Free download button."
  }
];
